models:
  dbt_project:
    staging:
      +materialized: view
      +schema: marts
    intermediate:
      +materialized: view
      +schema: marts
    marts:
      +materialized: table
      +schema: marts